services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres-pasword
      POSTGRES_USER: root 
      POSTGRES_DB: poc_database
    volumes:
      - pgdata:/var/lib/postgresql/data 
  pgadmin:
      image: dpage/pgadmin4
      ports:
        - 5050:80
      environment:
         PGADMIN_DEFAULT_EMAIL: "interns@mypoc.net"
         PGADMIN_DEFAULT_PASSWORD: "pgadminP@ssw0rd!"
 
volumes:
  pgdata:
